#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

synctimething::init_env
mkdir -p "$SYNCTIMETHING_DEV_APP_DATA_DIR"

cd "$SYNCTIMETHING_PROJECT_ROOT"
binary_path="$SYNCTIMETHING_DEV_STATE_DIR/sync-time-thing-harness"
go build -o "$binary_path" ./cmd/sync-time-thing
exec env \
  SYNCTIMETHING_LISTEN_ADDR="$SYNCTIMETHING_DEV_APP_ADDR" \
  SYNCTIMETHING_DATA_DIR="$SYNCTIMETHING_DEV_APP_DATA_DIR" \
  SYNCTIMETHING_ADMIN_USERNAME="$SYNCTIMETHING_DEV_ADMIN_USERNAME" \
  SYNCTIMETHING_ADMIN_PASSWORD="$SYNCTIMETHING_DEV_ADMIN_PASSWORD" \
  SYNCTIMETHING_TIMEZONE="$SYNCTIMETHING_DEV_TIMEZONE" \
  SYNCTIMETHING_ENCRYPTION_KEY="$SYNCTIMETHING_DEV_ENCRYPTION_KEY" \
  "$binary_path"
